# Dev environment overrides
global:
  namespace: wellnest-dev
  environment: dev
  urls:
    frontend: http://wellnest-dev.local
auth:
  replicaCount: 1
  image:
    repository: wellnest-auth-service
    tag: "07eb00f"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi
assessment:
  replicaCount: 1
  image:
    repository: wellnest-assessment-service
    tag: "ab553f7"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi
therapist:
  replicaCount: 1
  image:
    repository: wellnest-therapist-service
    tag: "d3d2437"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi
frontend:
  replicaCount: 1
  image:
    repository: wellnest-frontend
    tag: "1.0.0.0"
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  hpa:
    minReplicas: 1
    maxReplicas: 3
mongo:
  storage:
    size: 2Gi
nfs:
  enabled: false
gateway:
  hostname: wellnest-dev.local
