# MongoDB headless + ClusterIP services
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: {{ .Values.global.namespace }}
  labels:
    app: mongodb
    app.kubernetes.io/part-of: wellnest
    app.kubernetes.io/managed-by: Helm
    environment: {{ .Values.global.environment }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: mongodb
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: {{ .Values.global.namespace }}
  labels:
    app: mongodb
    app.kubernetes.io/part-of: wellnest
    app.kubernetes.io/managed-by: Helm
    environment: {{ .Values.global.environment }}
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
